//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeeReal.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeeReal.Language.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Receive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Combo_LogType_Rcv {
            get {
                return ResourceManager.GetString("Combo_LogType_Rcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Combo_LogType_Send {
            get {
                return ResourceManager.GetString("Combo_LogType_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send + Receive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Combo_LogType_SendRcv {
            get {
                return ResourceManager.GetString("Combo_LogType_SendRcv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recv과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Combo_Recv {
            get {
                return ResourceManager.GetString("Grid_Combo_Recv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Combo_Send {
            get {
                return ResourceManager.GetString("Grid_Combo_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Title_Enable {
            get {
                return ResourceManager.GetString("Grid_Title_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Title_Macro {
            get {
                return ResourceManager.GetString("Grid_Title_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Title_MacroName {
            get {
                return ResourceManager.GetString("Grid_Title_MacroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send/Recv과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Grid_Title_Type {
            get {
                return ResourceManager.GetString("Grid_Title_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Fail {
            get {
                return ResourceManager.GetString("Log_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Receive {
            get {
                return ResourceManager.GetString("Log_Receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Log_Send {
            get {
                return ResourceManager.GetString("Log_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SeeReal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the macro?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Macro_Save {
            get {
                return ResourceManager.GetString("Msg_Macro_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Name is empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_NoTitle {
            get {
                return ResourceManager.GetString("Msg_NoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Title_Save {
            get {
                return ResourceManager.GetString("Msg_Title_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Even과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Parity_Even {
            get {
                return ResourceManager.GetString("Parity_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Parity_None {
            get {
                return ResourceManager.GetString("Parity_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Odd과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Parity_Odd {
            get {
                return ResourceManager.GetString("Parity_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Language_English {
            get {
                return ResourceManager.GetString("Settings_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Korean과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Language_Korean {
            get {
                return ResourceManager.GetString("Settings_Language_Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Black {
            get {
                return ResourceManager.GetString("Settings_Style_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Blue {
            get {
                return ResourceManager.GetString("Settings_Style_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Brown {
            get {
                return ResourceManager.GetString("Settings_Style_Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Green과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Green {
            get {
                return ResourceManager.GetString("Settings_Style_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lime과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Lime {
            get {
                return ResourceManager.GetString("Settings_Style_Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Magenta과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Magenta {
            get {
                return ResourceManager.GetString("Settings_Style_Magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orange과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Orange {
            get {
                return ResourceManager.GetString("Settings_Style_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Pink {
            get {
                return ResourceManager.GetString("Settings_Style_Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Purple과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Purple {
            get {
                return ResourceManager.GetString("Settings_Style_Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Red과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Red {
            get {
                return ResourceManager.GetString("Settings_Style_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Silver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Silver {
            get {
                return ResourceManager.GetString("Settings_Style_Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Teal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Teal {
            get {
                return ResourceManager.GetString("Settings_Style_Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_White {
            get {
                return ResourceManager.GetString("Settings_Style_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yellow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Style_Yellow {
            get {
                return ResourceManager.GetString("Settings_Style_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Theme_Dark {
            get {
                return ResourceManager.GetString("Settings_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Theme_Light {
            get {
                return ResourceManager.GetString("Settings_Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Title_Language {
            get {
                return ResourceManager.GetString("Settings_Title_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sub Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Title_SubStyle {
            get {
                return ResourceManager.GetString("Settings_Title_SubStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Theme과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Title_Theme {
            get {
                return ResourceManager.GetString("Settings_Title_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tray Icon과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings_Title_TrayIcon {
            get {
                return ResourceManager.GetString("Settings_Title_TrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Btn_Apply {
            get {
                return ResourceManager.GetString("Tab_Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Btn_Cancel {
            get {
                return ResourceManager.GetString("Tab_Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Btn_Log_Find {
            get {
                return ResourceManager.GetString("Tab_Btn_Log_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Com Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Log {
            get {
                return ResourceManager.GetString("Tab_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Macro {
            get {
                return ResourceManager.GetString("Tab_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_MainTitle_Macro {
            get {
                return ResourceManager.GetString("Tab_MainTitle_Macro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_MainTitle_Settings {
            get {
                return ResourceManager.GetString("Tab_MainTitle_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Settings {
            get {
                return ResourceManager.GetString("Tab_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tile Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Tile_Color {
            get {
                return ResourceManager.GetString("Tab_Tile_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BaudRate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_BaudRate {
            get {
                return ResourceManager.GetString("Tab_Title_BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Bit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_DataBit {
            get {
                return ResourceManager.GetString("Tab_Title_DataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delay(ms)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Delay {
            get {
                return ResourceManager.GetString("Tab_Title_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flow Control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Flow {
            get {
                return ResourceManager.GetString("Tab_Title_Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Log_SaveEnable {
            get {
                return ResourceManager.GetString("Tab_Title_Log_SaveEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Save Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Log_SavePath {
            get {
                return ResourceManager.GetString("Tab_Title_Log_SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Save Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Log_SaveType {
            get {
                return ResourceManager.GetString("Tab_Title_Log_SaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Log_Token {
            get {
                return ResourceManager.GetString("Tab_Title_Log_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Macro Enable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_MacroEnable {
            get {
                return ResourceManager.GetString("Tab_Title_MacroEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parity Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Parity {
            get {
                return ResourceManager.GetString("Tab_Title_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_Port {
            get {
                return ResourceManager.GetString("Tab_Title_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Serial Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_SerialName {
            get {
                return ResourceManager.GetString("Tab_Title_SerialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Bit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Tab_Title_StopBit {
            get {
                return ResourceManager.GetString("Tab_Title_StopBit", resourceCulture);
            }
        }
    }
}
